export const WS_TYPES = {
  TOPIC_MESSAGE: "TOPIC_MESSAGE",
  FLIRT_MESSAGE: "FLIRT_MESSAGE",
  FLIRT_MATCHED: "FLIRT_MATCHED",
  FLIRT_ENDED: "FLIRT_ENDED",
  FLIRT_CANCELLED: "FLIRT_CANCELLED",
  PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
  FRIEND_REQUEST: "FRIEND_REQUEST",
  FRIEND_ACCEPTED: "FRIEND_ACCEPTED",
  CONVERSATION_UPDATED: "CONVERSATION_UPDATED",
  TOPIC_TYPING: "TOPIC_TYPING",
  TOPIC_PRESENCE: "TOPIC_PRESENCE",
  PRIVATE_TYPING: "PRIVATE_TYPING",
  PRIVATE_READ: "PRIVATE_READ",
  PRIVATE_MESSAGE_UPDATED: "PRIVATE_MESSAGE_UPDATED",
  FLIRT_TYPING: "FLIRT_TYPING",
  FLIRT_MESSAGE_UPDATED: "FLIRT_MESSAGE_UPDATED",
};

export const FLIRT_MATCH_TIMEOUT_SECONDS = 60;
